# Generated by Django 5.0.7 on 2024-07-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lens', '0002_queryform'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryform',
            name='reference',
            field=models.CharField(choices=[('1', 'INSTAGRAM'), ('2', 'GOOGLE ADS'), ('3', 'FACEBOOK'), ('4', 'TWITTER')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='queryform',
            name='service',
            field=models.CharField(choices=[('1', 'WEDDING'), ('2', 'CONCERT'), ('3', 'PORTRAIT'), ('4', 'PRODUCT')], default='1', max_length=20),
        ),
    ]
