# Generated by Django 5.0.7 on 2024-07-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lens', '0003_queryform_reference_queryform_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryform',
            name='message',
            field=models.TextField(default='this is first message'),
            preserve_default=False,
        ),
    ]
